### ISSUE TITLE
Menu buttons not working

### ISSUE THREAD

**Issue by Andrius86** [r4v10l1/NullHooks#1]

**Comment by r4v10l1** [comment]
Could you explain a bit more what is the problem?  
You can't select items in the menu or...?

**Comment by Andrius86** [comment]
Yes, for me menu is not working, I mean yes menu pop's up but when I try to turn any kind of function I can't.

**Comment by r4v10l1** [comment]
That's strange. I tried with different resolutions and it works fine as far as I know (injecting with different resolutions is fine, changing them not so much).

Did you compile the source or did you download the DLL from the release? If you just downloaded the file try downloading the project and compiling in `Release | x86`.

Don't know if it's what you tried but I recently added the capacity to enable and disable features by clicking the name itself (instead of just the checkbox), so make sure you have the latest version and try it when compiling.

**Comment by r4v10l1** [comment]
Fixed in ed128968c1f85ef59f0505ad17db7d79cf0e6090
