### ISSUE TITLE
good job + some Q

### ISSUE THREAD

**Issue by Rrhyast** [r4v10l1/NullHooks#3]
Great job, do u have plan to add any hvh features, or it's only maintained in legit mode?

Also cheat crash when I join casual servers, I don't know why.

**Comment by r4v10l1** [comment]
Thank you, and yes, I want to add as many features as I can, but rage is not my priority. As I explained in the README, my main goal is to learn, but contributions (like new features or improvements) are welcome.

About the crash on casual servers, does it crash every time you join a casual server or only sometimes? Are you using the [latest version](https://github.com/r4v10l1/NullHooks#compiling-from-source-recommended)? I played in casual servers a lot of times and although I had some problems in the past with the spectator list (which I fixed) I don't experience any crashes now.

If you can't fix it you can always try [debugging](https://docs.microsoft.com/en-us/visualstudio/debugger/attach-to-running-processes-with-the-visual-studio-debugger?view=vs-2022) and sending here a screenshot of the [callstack](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/viewing-the-call-stack-in-visual-studio).

**Comment by r4v10l1** [comment]
The triggerbot is one of the things I want to add in a near future. Right now I am trying to implement a color picker to the gui framework, because I don't want to use ImGui until I experience the pain of making my own gui.

The name ESP position can be easily changed from the source, but I like it where it is.
