### ISSUE TITLE
[misc]

### ISSUE THREAD

**Issue by coffin1337** [r4v10l1/NullHooks#40]
an edge bug works by bugging on an edge

**Comment by r4v10l1** [comment]
Thank you for this amazing contribution.

Just to make it clear, the edgebug still needs to be improved ([todo item](https://github.com/r4v10l1/NullHooks/blob/37fa2c6383eb510285f0a4e1b05edb72720165da/README.md?plain=1#L264)).

**Comment by coffin1337** [comment]
pseudo code

```
int pre_prediction_flags = local->flags();

prediction::start(cmd, local);

if (!(pre_prediction_flags & (e_player_states::fl_onground)) && local->flags() & (fl_onground))
	cmd->buttons |= in_duck;

prediction::end(cmd, local);
```

this would result in a simple edge bug feature, but you could make an "auto edge bug" by abusing engine prediction and running it to predict you players velocity, if at a certain velocity, duck or stand in your edge bug depending if you will hit it or not

**Comment by r4v10l1** [comment]
I am aware of this method, pretty much the same as jumpbug. I didn't use this because I was trying to add some kind of assistance, but clearly what I am using now is way worse than how it was before.

I will update the edgebug with a simpler method for now, but the prediction also needs to be improved.
