### ISSUE TITLE
[feature] Lua scripts

### ISSUE THREAD

**Issue by WhosOn** [r4v10l1/NullHooks#43]
A amazing feature that you should add with time, should be Lua/ Lua Scripts. Like in gamesense, otc v3, or nansosense

**Comment by r4v10l1** [comment]
I think it would be a cool feature, but I am not sure how hard it would be to implement.

**Comment by krispybyte** [comment]
Not that hard, just add LUA jit and make bindings for the api @r4v10l1

**Comment by r4v10l1** [comment]
Thank you for the info. I will look into it.

**Comment by krispybyte** [comment]
https://luajit.org/
https://github.com/ThePhD/sol2
i used sol for bindings when i implemented lua to a really old cheat of mine

**Comment by r4v10l1** [comment]
After doing some thinking, I have come to the conclusion that Lua is not the best feature for this cheat, because all the source code is public.

If you want to add a new feature, you can simply add it to the code and [make a pull request](https://github.com/r4v10l1/NullHooks/blob/main/CONTRIBUTING.md) in case you want to see it in the main repo, and if you wanna make a feature suggestion you can use the issue system.

Just to make it clear, I am not going to add it, but if someone wants to add it, they can contribute. Closing the issue for now.
